In [19]:
import numpy as np
import random

In [188]:
Arr1d=np.arange(1,21)

for i in range(1,len(Arr1d)+1):
    if i % 2==0:
        print(i,end=" ")
   


2 4 6 8 10 12 14 16 18 20 

In [195]:
Arr2_1d=np.arange(50,100)

print("mean",np.mean(Arr2_1d))

print("std",np.std(Arr2_1d))

print("median",np.median(Arr2_1d))

mean 74.5
std 14.430869689661812
median 74.5


In [44]:
arr5d=np.matrix('1 2 3 4 5; 1 2 3 4 5; 1 2 3 4 5; 1 2 3 4 5; 1 2 3 4 5 ')
arr51d=np.matrix('1 2 3 4 5; 1 2 3 4 5; 1 2 3 4 5; 1 2 3 4 5; 1 2 3 4 5 ')

arr5d * arr51d

matrix([[15, 30, 45, 60, 75],
        [15, 30, 45, 60, 75],
        [15, 30, 45, 60, 75],
        [15, 30, 45, 60, 75],
        [15, 30, 45, 60, 75]])

In [62]:
arr=np.arange(10,31)
arr[3:8]
arr[::2]
arr[::-1]

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
       13, 12, 11, 10])

In [100]:
arr21d=np.array([[10,20,30,40],
                 [50,60,70,80],
                 [90,100,110,120]])
arr21d[1]
arr21d[::,2:3:]
arr21d[1::,1:3:]


array([[ 60,  70],
       [100, 110]])

In [139]:
arr3d=np.arange(1,25)
arr3d=arr3d.reshape(2,3,4)
arr3d[1:2:,2:3:,:]
arr3d
arr3d[0:1:,1:2:,2:3:]
arr3d


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
l=[5,10,15,20,25,30]

convert=np.array(l)
out=[]

for i in convert:
    out.append(float(i))
print(np.array(out))



[ 5. 10. 15. 20. 25. 30.]


In [186]:
arr3x3=np.matrix('1 2 3 ; 4 5 6 ; 7 8 9 ')
arr3x3[:1:]
arr3x3[:1:-1]
arr3x3
arr3x3[1:2:,2:3:]

matrix([[6]])

In [ ]:
def median():
    