In [6]:
!pip3 install numpy


[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: /Library/Frameworks/Python.framework/Versions/3.14/bin/python3.14 -m pip install --upgrade pip


In [3]:
import numpy as np

```python
2D array
syntax: variable[ (row slice) , (column slice) ]
or
variable[start :end :step,  start  : end  : step ]
```

In [8]:
arr2=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

arr2[::,::] 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2[::,1:2:]

array([[2],
       [5],
       [8]])

```python
3D ARRAY
syntax: variable[depth slice , row slice , column slice ]
or
variable[start :end :step, start :end :step,  start  : end  : step ]

```

In [10]:
ARR3d=np.array([
                [[1,2,3],
                 [4,5,6]],
                
                [[7,8,9],
                 [10,11,12]],
                
                [[13,14,15],
                 [16,17,18]]
                
                ])

In [11]:
ARR3d[1::,1:2:,:1:-1] 

array([[[12]],

       [[18]]])

In [12]:
arr1=[]
arr=[[[1,2,3,4],[1,1,34,2]]]
for i in arr:
    for j in i:
        for k in j:
            arr1.append(k)
arr1
   
    

[1, 2, 3, 4, 1, 1, 34, 2]

In [13]:
#RECURRSION

def flatten(arr):
    result = []
    for x in arr:
        if isinstance(x, list):
            result.extend(flatten(x))
        else:
            result.append(x)
    return result


arr = [[[1, 2, 3, 4], [1, 1, 34, 2]]]

print(flatten(arr))

[1, 2, 3, 4, 1, 1, 34, 2]


## **FANCY Indexing** <hr>

```python 
Fancy indexing in NumPy refers to accessing or modifying multiple array elements at once by passing lists or arrays of integer indices. Unlike basic slicing (like arr[1:5]), fancy indexing allows you to extract elements that are non-adjacent, scattered, or completely out of order
```

# **syntax: variable[Collection(list,np.arrays)]**

But The collection should be list in this the collection should have a integer only values

```python

arr = np.array([1,2,3,4,5])

arr[[3,1,4]]

#output
array([4,2,5])


```

In [14]:
arr = np.array([1,2,3,4,5])
arr[[3,1,4]]

array([4, 2, 5])

In [15]:
arr3d=np.array([[[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[1,2,3],
               [4,5,6],
               [7,8,9]],
               ]])

## **OPERATIONS ON ARRAY** <hr>

## ADDITION 


In [27]:
arr1=np.array([1,2,3,4,5])
arr1+10 # this process is known as BROADCASTING 

array([11, 12, 13, 14, 15])

In [17]:
arr1=np.array(["helloo","he"])
arr1+" world"

array(['helloo world', 'he world'], dtype='<U12')

In [21]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1+arr2

array([ 7,  9, 11, 13, 15])

# **VVVVV IMP NOTE**
```python
In addition both the array should of same shape and dtype (data type ) should suppport addition
subtraction follows the same rule as same as addition 
```

In [1]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9])#different DIMENTIONS
arr1+arr2
#error because different length 

NameError: name 'np' is not defined

```python



copy method since in numpy also we can modify , performing the general copy  will led to issue changes in one variable will effect the other variable . 
So we use copy method to copy numpy . 




```

In [7]:
arr1 = np.random.randint(10,100,12)
arr2 = np.random.randint(1,1000,20).reshape((2,10))
arr3 = arr2.reshape((2,2,5))

In [9]:
arrx=arr1
arrx

array([30, 72, 49, 11, 57, 84, 30, 78, 71, 73, 94, 85])

In [12]:
arrx[10]=1000
arrx

array([  30,   72,   49,   11,   57,   84,   30,   78,   71,   73, 1000,
         85])

In [14]:
arr1 # modifucation in array is affecting the both the array

array([  30,   72,   49,   11,   57,   84,   30,   78,   71,   73, 1000,
         85])

```python

Copy: modification will not affect both arrays
syntax: arr.copy()

```

In [19]:


arrx=arr1.copy()
arrx[2]=300




In [17]:
arrx

array([  30,   72,  300,   11,   57,   84,   30,   78,   71,   73, 1000,
         85])

In [18]:
arr1

array([  30,   72,   49,   11,   57,   84,   30,   78,   71,   73, 1000,
         85])

In [ ]:
arr2x=arr2.copy

```python


View : If modification will affect both arrays but address will be different
syntax: arr.view()


```

In [22]:
arrx = arr1.view()

arrx[0]=1

arrx

array([   1,   72,   49,   11,   57,   84,   30,   78,   71,   73, 1000,
         85])

In [23]:
arr1

array([   1,   72,   49,   11,   57,   84,   30,   78,   71,   73, 1000,
         85])

1. np.min()
```python
it is use to calculate the minmum value present in an array 
```

In [26]:
print(np.std.__doc__)


Compute the standard deviation along the specified axis.

Returns the standard deviation, a measure of the spread of a distribution,
of the array elements. The standard deviation is computed for the
flattened array by default, otherwise over the specified axis.

Parameters
----------
a : array_like
    Calculate the standard deviation of these values.
axis : None or int or tuple of ints, optional
    Axis or axes along which the standard deviation is computed. The
    default is to compute the standard deviation of the flattened array.
    If this is a tuple of ints, a standard deviation is performed over
    multiple axes, instead of a single axis or all the axes as before.
dtype : dtype, optional
    Type to use in computing the standard deviation. For arrays of
    integer type the default is float64, for arrays of float types it is
    the same as the array type.
out : ndarray, optional
    Alternative output array in which to place the result. It must have
    the same shape as t

SyntaxError: unexpected character after line continuation character (3292709926.py, line 1)